from utils.calculator import soucet
print("Toto je můj první push po nastavení repozitaře!")
print("Toto je nová změna")
print("Hello z baličku helloworld")
print("Test commit panelu")
print(soucet(2, 3))
print("Commit z lekce 15")
print("Změna pro text push")
print("Změna z Git GUI test")
print("Změna přes GitGUI 2")
print("Změna ve větvi nava-vetev")
print("Test z GitHub Desktop")
print("Změna z větve nova-zmena")